# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_netjsonconfig', '0017_openvpn_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('is_indoor', models.NullBooleanField()),
                ('notes', models.TextField(blank=True)),
                ('geom', djgeojson.fields.PointField()),
                ('config', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='django_netjsonconfig.Config')),
            ],
        ),
    ]
