# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
