# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:16
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20161113_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
