# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20161113_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='device',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='device',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='device',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='ZIP/Postal Code'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=256, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Model name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Administration notes'),
        ),
    ]
