# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:19
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20161115_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='geom',
            field=djgeojson.fields.PointField(help_text=' '),
        ),
    ]
