# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectd_rest', '0001_initial'),
        ('devices', '0006_auto_20161117_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphManager',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devices.Device')),
                ('cpugraphs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_graphmanager', to='collectd_rest.GraphGroup')),
                ('interfacegraphs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interface_graphmanager', to='collectd_rest.GraphGroup')),
                ('loadgraphs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_graphmanager', to='collectd_rest.GraphGroup')),
                ('memorygraphs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_graphmanager', to='collectd_rest.GraphGroup')),
            ],
        ),
    ]
